# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from typing import ClassVar

from psycopg import AsyncConnection, Connection
from psycopg.rows import args_row as _args_row

from .. import types as _db_types
from .._core import Statement
from .._runtime import fetch_single as _fetch_single
from ..sync._runtime import fetch_single as _fetch_single_sync


@dataclass(frozen=True, slots=True)
class InsertAlbumRow:
    id: int


@dataclass(frozen=True, slots=True)
class InsertAlbum(Statement[InsertAlbumRow]):
    name: str
    released: date
    format: _db_types.AlbumFormat
    recording: _db_types.RecordingInfo

    SQL: ClassVar[str] = """\
insert into album (name, released, format, recording)
values (%(name)s, %(released)s, %(format)s, %(recording)s)
returning id
"""

    async def execute(self, conn: AsyncConnection[object]) -> InsertAlbumRow:
        params: dict[str, object] = {
            "name": self.name,
            "released": self.released,
            "format": self.format,
            "recording": self.recording,
        }
        return await _fetch_single(conn, self.SQL, params, _args_row(InsertAlbumRow))

    def execute_sync(self, conn: Connection[object]) -> InsertAlbumRow:
        params: dict[str, object] = {
            "name": self.name,
            "released": self.released,
            "format": self.format,
            "recording": self.recording,
        }
        return _fetch_single_sync(conn, self.SQL, params, _args_row(InsertAlbumRow))
