# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar

from psycopg import AsyncConnection, Connection
from psycopg.rows import args_row as _args_row

from .. import types as _db_types
from .._core import Statement
from .._runtime import fetch_many as _fetch_many
from ..sync._runtime import fetch_many as _fetch_many_sync


@dataclass(frozen=True, slots=True)
class SelectAlbumWithTracksRow:
    id: int
    name: str
    tracks: list[_db_types.TrackInfo]
    disc: _db_types.DiscInfo | None


@dataclass(frozen=True, slots=True)
class SelectAlbumWithTracks(Statement[list[SelectAlbumWithTracksRow]]):
    id: int

    SQL: ClassVar[str] = """\
select id, name, tracks, disc
from album
where id = %(id)s
"""

    async def execute(self, conn: AsyncConnection[object]) -> list[SelectAlbumWithTracksRow]:
        params: dict[str, object] = {
            "id": self.id,
        }
        return await _fetch_many(conn, self.SQL, params, _args_row(SelectAlbumWithTracksRow))

    def execute_sync(self, conn: Connection[object]) -> list[SelectAlbumWithTracksRow]:
        params: dict[str, object] = {
            "id": self.id,
        }
        return _fetch_many_sync(conn, self.SQL, params, _args_row(SelectAlbumWithTracksRow))
