# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar

from psycopg import AsyncConnection, Connection
from psycopg.rows import args_row as _args_row

from .._core import Statement
from .._runtime import fetch_many as _fetch_many
from ..sync._runtime import fetch_many as _fetch_many_sync


@dataclass(frozen=True, slots=True)
class SelectGenreByArtistRow:
    id: int
    name: str


@dataclass(frozen=True, slots=True)
class SelectGenreByArtist(Statement[list[SelectGenreByArtistRow]]):
    artist: int

    SQL: ClassVar[str] = """\
select id, genre.name
from genre
left join album_genre on album_genre.genre = genre.id
left join album_artist on album_artist.album = album_genre.album
where album_artist.artist = %(artist)s
"""

    async def execute(self, conn: AsyncConnection[object]) -> list[SelectGenreByArtistRow]:
        params: dict[str, object] = {
            "artist": self.artist,
        }
        return await _fetch_many(conn, self.SQL, params, _args_row(SelectGenreByArtistRow))

    def execute_sync(self, conn: Connection[object]) -> list[SelectGenreByArtistRow]:
        params: dict[str, object] = {
            "artist": self.artist,
        }
        return _fetch_many_sync(conn, self.SQL, params, _args_row(SelectGenreByArtistRow))
