# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from typing import ClassVar

from psycopg import AsyncConnection, Connection
from psycopg.rows import args_row as _args_row

from .. import types as _db_types
from .._core import Statement
from .._runtime import fetch_many as _fetch_many
from ..sync._runtime import fetch_many as _fetch_many_sync


@dataclass(frozen=True, slots=True)
class SelectAlbumByFormatRow:
    id: int
    name: str
    released: date | None
    format: _db_types.AlbumFormat | None
    recording: _db_types.RecordingInfo | None


@dataclass(frozen=True, slots=True)
class SelectAlbumByFormat(Statement[list[SelectAlbumByFormatRow]]):
    format: _db_types.AlbumFormat

    SQL: ClassVar[str] = """\
select
  id,
  name,
  released,
  format,
  recording
from album
where format = %(format)s
"""

    async def execute(self, conn: AsyncConnection[object]) -> list[SelectAlbumByFormatRow]:
        params: dict[str, object] = {
            "format": self.format,
        }
        return await _fetch_many(conn, self.SQL, params, _args_row(SelectAlbumByFormatRow))

    def execute_sync(self, conn: Connection[object]) -> list[SelectAlbumByFormatRow]:
        params: dict[str, object] = {
            "format": self.format,
        }
        return _fetch_many_sync(conn, self.SQL, params, _args_row(SelectAlbumByFormatRow))
