# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from typing import ClassVar

from psycopg import AsyncConnection, Connection
from psycopg.rows import args_row as _args_row

from .. import types as _db_types
from .._core import Statement
from .._runtime import fetch_optional as _fetch_optional
from ..sync._runtime import fetch_optional as _fetch_optional_sync


@dataclass(frozen=True, slots=True)
class SelectAlbumByIdRow:
    id: int
    name: str
    released: date | None
    format: _db_types.AlbumFormat | None
    recording: _db_types.RecordingInfo | None
    tracks: list[_db_types.TrackInfo | None] | None
    disc: _db_types.DiscInfo | None


@dataclass(frozen=True, slots=True)
class SelectAlbumById(Statement[SelectAlbumByIdRow | None]):
    id: int | None

    SQL: ClassVar[str] = """\
-- Example of a query selecting 0 or 1 row.
select *
from album
where id = %(id)s
limit 1
"""

    async def execute(self, conn: AsyncConnection[object]) -> SelectAlbumByIdRow | None:
        params: dict[str, object] = {
            "id": self.id,
        }
        return await _fetch_optional(conn, self.SQL, params, _args_row(SelectAlbumByIdRow))

    def execute_sync(self, conn: Connection[object]) -> SelectAlbumByIdRow | None:
        params: dict[str, object] = {
            "id": self.id,
        }
        return _fetch_optional_sync(conn, self.SQL, params, _args_row(SelectAlbumByIdRow))
