# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime
from typing import ClassVar

from psycopg import AsyncConnection, Connection
from psycopg.rows import args_row as _args_row

from .. import types as _db_types
from .._core import Statement
from .._runtime import fetch_many as _fetch_many
from ..sync._runtime import fetch_many as _fetch_many_sync


@dataclass(frozen=True, slots=True)
class SelectAlbumWithFiltersRow:
    id: int
    name: str | None
    released: date | None
    format: _db_types.AlbumFormat | None
    recording: _db_types.RecordingInfo | None
    tracks: list[_db_types.TrackInfo] | None
    disc: _db_types.DiscInfo | None


@dataclass(frozen=True, slots=True)
class SelectAlbumWithFilters(Statement[list[SelectAlbumWithFiltersRow]]):
    include_name: bool
    include_released: bool
    include_format: bool
    include_recording: bool
    include_tracks: bool
    include_disc: bool
    artist_name: str | None
    genre_name: str | None
    format: _db_types.AlbumFormat | None
    released_after: datetime | None
    name_like: str | None
    order_by_name: bool
    order_by_released: bool

    SQL: ClassVar[str] = """\
-- Demonstrates static query equivalent of dynamic field selection.
-- Boolean flags control which fields are included in the result,
-- returning NULL for fields the caller opts out of.
-- Also demonstrates optional filters and ordering criteria.
SELECT
  album.id,
  CASE WHEN %(include_name)s THEN album.name END AS name,
  CASE WHEN %(include_released)s THEN album.released END AS released,
  CASE WHEN %(include_format)s THEN album.format END AS format,
  CASE WHEN %(include_recording)s THEN album.recording END AS recording,
  CASE WHEN %(include_tracks)s THEN album.tracks END AS tracks,
  CASE WHEN %(include_disc)s THEN album.disc END AS disc
FROM album
LEFT JOIN album_artist ON album_artist.album = album.id
LEFT JOIN artist ON artist.id = album_artist.artist
LEFT JOIN album_genre ON album_genre.album = album.id
LEFT JOIN genre ON genre.id = album_genre.genre
WHERE
  (%(artist_name)s::text IS NULL OR artist.name = %(artist_name)s)
  AND (%(genre_name)s::text IS NULL OR genre.name = %(genre_name)s)
  AND (%(format)s::album_format IS NULL OR album.format = %(format)s)
  AND (%(released_after)s::timestamp IS NULL OR album.released >= %(released_after)s)
  AND (%(name_like)s::text IS NULL OR album.name LIKE %(name_like)s)
ORDER BY
  CASE WHEN %(order_by_name)s THEN album.name END ASC,
  CASE WHEN %(order_by_released)s THEN album.released END DESC
"""

    async def execute(self, conn: AsyncConnection[object]) -> list[SelectAlbumWithFiltersRow]:
        params: dict[str, object] = {
            "include_name": self.include_name,
            "include_released": self.include_released,
            "include_format": self.include_format,
            "include_recording": self.include_recording,
            "include_tracks": self.include_tracks,
            "include_disc": self.include_disc,
            "artist_name": self.artist_name,
            "genre_name": self.genre_name,
            "format": self.format,
            "released_after": self.released_after,
            "name_like": self.name_like,
            "order_by_name": self.order_by_name,
            "order_by_released": self.order_by_released,
        }
        return await _fetch_many(conn, self.SQL, params, _args_row(SelectAlbumWithFiltersRow))

    def execute_sync(self, conn: Connection[object]) -> list[SelectAlbumWithFiltersRow]:
        params: dict[str, object] = {
            "include_name": self.include_name,
            "include_released": self.include_released,
            "include_format": self.include_format,
            "include_recording": self.include_recording,
            "include_tracks": self.include_tracks,
            "include_disc": self.include_disc,
            "artist_name": self.artist_name,
            "genre_name": self.genre_name,
            "format": self.format,
            "released_after": self.released_after,
            "name_like": self.name_like,
            "order_by_name": self.order_by_name,
            "order_by_released": self.order_by_released,
        }
        return _fetch_many_sync(conn, self.SQL, params, _args_row(SelectAlbumWithFiltersRow))
