# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from typing import ClassVar

from psycopg import AsyncConnection, Connection

from .._core import Statement
from .._runtime import execute_rows_affected as _execute_rows_affected
from ..sync._runtime import execute_rows_affected as _execute_rows_affected_sync


@dataclass(frozen=True, slots=True)
class UpdateAlbumReleased(Statement[int]):
    released: date | None
    id: int

    SQL: ClassVar[str] = """\
update album
set released = %(released)s
where id = %(id)s
"""

    async def execute(self, conn: AsyncConnection[object]) -> int:
        params: dict[str, object] = {
            "released": self.released,
            "id": self.id,
        }
        return await _execute_rows_affected(conn, self.SQL, params)

    def execute_sync(self, conn: Connection[object]) -> int:
        params: dict[str, object] = {
            "released": self.released,
            "id": self.id,
        }
        return _execute_rows_affected_sync(conn, self.SQL, params)
