# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from typing import ClassVar

from psycopg import AsyncConnection, Connection
from psycopg.rows import args_row as _args_row

from .. import types as _db_types
from .._core import Statement
from .._runtime import fetch_many as _fetch_many
from ..sync._runtime import fetch_many as _fetch_many_sync


@dataclass(frozen=True, slots=True)
class UpdateAlbumRecordingReturningRow:
    id: int
    name: str
    released: date | None
    format: _db_types.AlbumFormat | None
    recording: _db_types.RecordingInfo | None
    tracks: list[_db_types.TrackInfo] | None
    disc: _db_types.DiscInfo | None


@dataclass(frozen=True, slots=True)
class UpdateAlbumRecordingReturning(Statement[list[UpdateAlbumRecordingReturningRow]]):
    recording: _db_types.RecordingInfo | None
    id: int

    SQL: ClassVar[str] = """\
-- Update album recording information
update album
set recording = %(recording)s
where id = %(id)s
returning *
"""

    async def execute(self, conn: AsyncConnection[object]) -> list[UpdateAlbumRecordingReturningRow]:
        params: dict[str, object] = {
            "recording": self.recording,
            "id": self.id,
        }
        return await _fetch_many(conn, self.SQL, params, _args_row(UpdateAlbumRecordingReturningRow))

    def execute_sync(self, conn: Connection[object]) -> list[UpdateAlbumRecordingReturningRow]:
        params: dict[str, object] = {
            "recording": self.recording,
            "id": self.id,
        }
        return _fetch_many_sync(conn, self.SQL, params, _args_row(UpdateAlbumRecordingReturningRow))
