# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

from psycopg import AsyncConnection, Connection

from . import types as _db_types


async def register_types(conn: AsyncConnection[object]) -> None:
    await _db_types.album_format.register(conn)
    await _db_types.recording_info.register(conn)
    await _db_types.track_info.register(conn)
    await _db_types.disc_info.register(conn)


def register_types_sync(conn: Connection[object]) -> None:
    _db_types.album_format.register_sync(conn)
    _db_types.recording_info.register_sync(conn)
    _db_types.track_info.register_sync(conn)
    _db_types.disc_info.register_sync(conn)
