# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from __future__ import annotations

import keyword
from collections.abc import Callable, Sequence
from dataclasses import fields, is_dataclass
from typing import Any, LiteralString

from psycopg import AsyncConnection
from psycopg.rows import BaseRowFactory
from psycopg.types.composite import CompositeInfo

from ._core import NoRowError

_Params = dict[str, object]


async def fetch_optional[T](
    conn: AsyncConnection[object],
    sql: LiteralString,
    params: _Params,
    row_factory: BaseRowFactory[T],
) -> T | None:
    async with conn.cursor(row_factory=row_factory) as cur:
        _ = await cur.execute(sql, params)
        return await cur.fetchone()


async def fetch_single[T](
    conn: AsyncConnection[object],
    sql: LiteralString,
    params: _Params,
    row_factory: BaseRowFactory[T],
) -> T:
    async with conn.cursor(row_factory=row_factory) as cur:
        _ = await cur.execute(sql, params)
        row = await cur.fetchone()
    if row is None:
        raise NoRowError(sql)
    return row


async def fetch_many[T](
    conn: AsyncConnection[object],
    sql: LiteralString,
    params: _Params,
    row_factory: BaseRowFactory[T],
) -> list[T]:
    async with conn.cursor(row_factory=row_factory) as cur:
        _ = await cur.execute(sql, params)
        return await cur.fetchall()


async def execute_rows_affected(
    conn: AsyncConnection[object],
    sql: LiteralString,
    params: _Params,
) -> int:
    async with conn.cursor() as cur:
        _ = await cur.execute(sql, params)
        return cur.rowcount


async def execute_void(
    conn: AsyncConnection[object],
    sql: LiteralString,
    params: _Params,
) -> None:
    async with conn.cursor() as cur:
        _ = await cur.execute(sql, params)


type _ObjectMaker[T] = Callable[[Sequence[Any], CompositeInfo], T]
type _SequenceMaker[T] = Callable[[T, CompositeInfo], Sequence[Any]]


def dataclass_callbacks[T](cls: type[T]) -> tuple[_ObjectMaker[T], _SequenceMaker[T]]:
    if not is_dataclass(cls):
        raise TypeError(f"{cls.__name__} must be a dataclass")

    model_fields = fields(cls)
    model_names = tuple(field.name for field in model_fields)

    def _python_name(name: str) -> str:
        if keyword.iskeyword(name):
            return f"{name}_"
        return name

    def make_object(values: Sequence[Any], info: CompositeInfo) -> T:
        names = tuple(_python_name(name) for name in info.field_names)
        assert names == model_names
        assert len(values) == len(model_fields)
        return cls(**dict(zip(names, values, strict=True)))

    def make_sequence(obj: T, info: CompositeInfo) -> Sequence[Any]:
        names = tuple(_python_name(name) for name in info.field_names)
        assert names == model_names
        return tuple(getattr(obj, field.name) for field in model_fields)

    return make_object, make_sequence
