# @generated by python.gen (pGenie); regeneration overwrites manual changes.
# SPDX-FileCopyrightText: 2026 Viacheslav Shvets
# SPDX-License-Identifier: MIT-0

from enum import StrEnum

from psycopg import AsyncConnection, Connection
from psycopg.types.enum import EnumInfo, register_enum


class AlbumFormat(StrEnum):
    VINYL = "Vinyl"
    CD = "CD"
    CASSETTE = "Cassette"
    DIGITAL = "Digital"
    DVD_AUDIO = "DVD-Audio"
    SACD = "SACD"


_album_format_pg_name = "public.album_format"


async def register(conn: AsyncConnection[object]) -> None:
    album_format_info = await EnumInfo.fetch(conn, _album_format_pg_name)
    if album_format_info is None:
        raise LookupError(f"enum type {_album_format_pg_name!r} not found; cannot register it")
    register_enum(
        album_format_info,
        conn,
        AlbumFormat,
        mapping={member: member.value for member in AlbumFormat},
    )


def register_sync(conn: Connection[object]) -> None:
    album_format_info = EnumInfo.fetch(conn, _album_format_pg_name)
    if album_format_info is None:
        raise LookupError(f"enum type {_album_format_pg_name!r} not found; cannot register it")
    register_enum(
        album_format_info,
        conn,
        AlbumFormat,
        mapping={member: member.value for member in AlbumFormat},
    )
